# Generated by Codex on 2026-08-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("schedule", "Schedule"),
                            ("requirements", "Requirements"),
                            ("habits", "Habits"),
                            ("budget", "Budget"),
                            ("debt", "Debt"),
                            ("meals", "Meals"),
                            ("career", "Career"),
                            ("inventory", "Inventory"),
                            ("messages", "Messages"),
                        ],
                        max_length=32,
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["position", "key"],
                "unique_together": {("user", "key")},
            },
        ),
    ]
